[FIX] viin_brand_website: test_pylint
```
odoo.addons.test_pylint.tests.test_pylint: FAIL: TestPyLint.test_pylint
Traceback (most recent call last):
File "/data/build/Viindoo-tvtmaaddons-19.0/test_pylint/tests/test_pylint.py",
line 179, in test_pylint
self.fail("pylint test failed:\n" + (b"\n" + out + b"\n" +
err).decode('utf-8').strip())
AssertionError: pylint test failed:
************* Module
viin_brand_website.tests.test_website_favicon_not_preempted
Same Odoo module absolute import. You should use relative import with
"." instead of "odoo.addons.viin_brand_website" (W8150) at
rb-c6270b8-223806/viin_brand_website/tests/test_website_favicon_not_preempted.py:167
```